# Generated by Django 4.1.7 on 2023-03-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDisplay',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_modified', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
    ]
