# Generated by Django 4.1.7 on 2023-05-16 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedisplay',
            name='qr_code_img',
            field=models.ImageField(editable=False, upload_to='API/qr_codes/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
