# Generated by Django 4.1.7 on 2023-05-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_productchange_id_productchange_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedisplay',
            name='qr_code',
            field=models.CharField(editable=False, max_length=500),
        ),
    ]
