# Generated by Django 4.1.7 on 2023-04-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_product_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'last_modified'], 'verbose_name': 'Product'},
        ),
        migrations.AddField(
            model_name='pricedisplay',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.product'),
        ),
    ]
