# Generated by Django 4.1.7 on 2023-04-19 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': ['name', '-last_modified'], 'ordering': ['name', '-last_modified'], 'verbose_name': 'Product'},
        ),
    ]
