# Generated by Django 4.1.7 on 2023-05-31 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_pricedisplay_qr_code_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedisplay',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.product'),
        ),
        migrations.AlterField(
            model_name='pricedisplay',
            name='qr_code_img',
            field=models.ImageField(editable=False, upload_to=''),
        ),
    ]
