# Generated by Django 4.1.7 on 2023-05-31 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_pricedisplay_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedisplay',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.product'),
        ),
    ]
